# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c7ca70dbf90de5846bbbd3d35a8c50a65d8d2109b4b39f7fd3cdbf195c012b7907398c58c3ddc9634d758b348027297476619eb507369ec95fc790a93ddd77da

test:
  secret_key_base: 4dec02b35fc84fe9b32b987218b8b02da1e4ed674e9255a3b8234e48b3e6ba88d7e4f4dab0b10a3f9ad6c7e671b626b7674df9a7bb1274b049f171c3e554d499

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
